language: go
sudo: false
go:
  - 1.3
  - 1.4
  - 1.5
  - tip
before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
install:
  - go get -v -t .
script:
  - go test -v .
  - go vet ./...
  - golint ./...